apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-apache
  labels:
    app: my-apache
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-apache
  template:
    metadata:
      labels:
        app: my-apache
    spec:
      containers:
      - name: my-apache
        image: httpd:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
